name: CI/CD for Iris Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your local machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt (
            pip install -r requirements.txt
          ) else (
            echo "No requirements.txt found"
          )

      - name: Stop existing Streamlit (if running)
        shell: pwsh
        run: |
          Get-Process -Name "streamlit" -ErrorAction SilentlyContinue | Stop-Process -Force
          echo "Stopped any existing Streamlit process."

      - name: Run Streamlit app
        shell: pwsh
        run: |
          Start-Process "streamlit" -ArgumentList "run iris_streamlit.py" -NoNewWindow
          echo "Streamlit app started successfully."
